### ISSUE TITLE
Delete jobs Throwing an exception when dealing with a large amount of id's.

### ISSUE THREAD

**Issue by marcoteodoro** [enterspeedhq/enterspeed-source-umbraco-cms#108]
Hi Guys, 

`EnterspeedJobRepository.Delete` action is throwing an exception when dealing with a large amount of id's. 

![image](https://github.com/enterspeedhq/enterspeed-source-umbraco-cms/assets/3866444/7e4014b5-f141-492b-9649-4d0e5bbe689b)

https://github.com/enterspeedhq/enterspeed-source-umbraco-cms/blob/b327587052553b3445d1f215ab9ae163e7a0d4f1/src/Enterspeed.Source.UmbracoCms/Data/Repositories/EnterspeedJobRepository.cs#L108-L113

**Comment by emilras** [comment]
@marcoteodoro Thank you for the detailed report!

As we have discussed via Slack, the issue is due to too many failed jobs for a given node. For others reading along on this issue, the shortterm fix is to clean up the EnterspeedJobs table for old failed jobs. We will add a longterm fix so something similar can't happen again.
